## **Lecture 6. Linear Algebra and Systems of Linear Equations** 
### **6.2 Linear Transformations** 

For vectors $x$ and $y$, and scalars $a$ and $b$, it is sufficient to say that a function, $F$, is a **linear transformation** if  

<br>

$$
F(ax + by) = aF(x) + bF(y).
$$

<br>

<font color="magenta">**TRY IT!**</font> Let $x$ be a vector and let $F(x)$ be defined by $F(x) =y= Ax$ where $A$ is a rectangular matrix of appropriate size. Show that $F(x)$ is a linear transformation.


<font color="cyan">**Four important subpsaces associated with $y = Ax$:**</font>


* $x \in \mathcal{C}(\mathbf{A^T}) \subset {\mathbb{R^{n}}}$<br>  $x$ in row space
* $x_{null} \in \mathcal{N}(\mathbf{A}) \subset {\mathbb{R^{n}}}$<br> $x_{null}$ in null space 


* $y \in \mathcal{C}(\mathbf{A}) \subset {\mathbb{R^{m}}}$<br>  $y$ in column space
* $y_{leftnull} \in \mathcal{N}(\mathbf{A^T}) \subset {\mathbb{R^{m}}}$<br> $y_{leftnull}$ in left null space 

<font color="magenta">**TRY IT!**</font><br> Let $A = [[1, 0, 0], [0, 1, 0], [0, 0, 0]]$ and let the domain of $A$ be ${\mathbb{R}}^3$. Characterize the range (column space) and nullspace of $A$.
  
Let $v = [x,y,z]$ be a vector in ${\mathbb{R}}^3$. Then $u = Av$ is the vector $u = [x,y,0]$. Since $x,y\in {\mathbb{R}}$, the range of $A$ is the $x$-$y$ plane at $z = 0$.

Let $v = [0,0,z]$ for $z\in {\mathbb{R}}$. Then $u = Av$ is the vector $u = [0, 0, 0]$. Therefore, the nullspace of $A$ is the $z$-axis (i.e., the set of vectors $[0,0,z]$ $z\in {\mathbb{R}}$).

Therefore, this linear transformation "flattens" any $z$-component from a vector.

In [ ]:
"""
Example 6.2.1:
SVD to find four fundamental basis, Null space as example. 
"""
import numpy as np
from numpy.linalg import matrix_rank
from numpy.linalg import svd

A = np.array([[1, 0, 0], [2, 1, 0], [5, 0, 1]])@np.array([[1, 3, 0, 5], [0, 0, 1, 6], [0, 0, 0, 0]])
U, S, VH = svd(A)
r = matrix_rank(A)

print("rank = ", r)
print("U = \n", U) 
print("S = \n", S) 
print("VH = \n", VH) 

[[1 0]
 [0 1]]
[[1 0]
 [0 1]]
rank =  2
U = 
 [[ 0. -1.]
 [-1.  0.]]
S = 
 [1. 1.]
VH = 
 [[-1. -0.]
 [ 0.  1.]]


#### <font color=red>**Homework**</font> 

1. Refer to https://timbaumann.info/svd-image-compression-demo, please calcute the rank of France and Greece Flag.

