## **Lecture 6. Linear Algebra and Systems of Linear Equations** 
### **6.2 Linear Transformations** 

For vectors $x$ and $y$, and scalars $a$ and $b$, it is sufficient to say that a function, $F$, is a **linear transformation** if  

<br>

$$
F(ax + by) = aF(x) + bF(y).
$$

<br>

<font color="magenta">**TRY IT!**</font> Let $x$ be a vector and let $F(x)$ be defined by $F(x) =y= Ax$ where $A$ is a rectangular matrix of appropriate size. Show that $F(x)$ is a linear transformation.


<font color="cyan">**Four important subpsaces associated with $y = Ax$:**</font>


* $x \in \mathcal{C}(\mathbf{A^T}) \subset {\mathbb{R^{n}}}$<br>  $x$ in row space
* $x_{null} \in \mathcal{N}(\mathbf{A}) \subset {\mathbb{R^{n}}}$<br> $x_{null}$ in null space 


* $y \in \mathcal{C}(\mathbf{A}) \subset {\mathbb{R^{m}}}$<br>  $y$ in column space
* $y_{leftnull} \in \mathcal{N}(\mathbf{A^T}) \subset {\mathbb{R^{m}}}$<br> $y_{leftnull}$ in left null space 

<font color="magenta">**TRY IT!**</font><br> Let $A = [[1, 0, 0], [0, 1, 0], [0, 0, 0]]$ and let the domain of $A$ be ${\mathbb{R}}^3$. Characterize the range (column space) and nullspace of $A$.
  
Let $v = [x,y,z]$ be a vector in ${\mathbb{R}}^3$. Then $u = Av$ is the vector $u = [x,y,0]$. Since $x,y\in {\mathbb{R}}$, the range of $A$ is the $x$-$y$ plane at $z = 0$.

Let $v = [0,0,z]$ for $z\in {\mathbb{R}}$. Then $u = Av$ is the vector $u = [0, 0, 0]$. Therefore, the nullspace of $A$ is the $z$-axis (i.e., the set of vectors $[0,0,z]$ $z\in {\mathbb{R}}$).

Therefore, this linear transformation "flattens" any $z$-component from a vector.

In [6]:
"""
Example 6.2.1:
Given matrix A (m by n), find its reduced row echelon form R.
In practice for factorization, we use A = QR (single basis) and SVD(A) (dual basis) 
"""
import numpy as np

def row_echelon(A):
    # If matrix A has no columns or rows, it is already in RREF, so we return itself
    r, c = A.shape
    if r == 0 or c == 0:
        return A
    
    # We search for non-zero element in the first column
    for i in range(len(A)):
        if A[i, 0] != 0:
            break
    else:
        # If all elements in the first column are zero, perform RREF on matrix from second column
        B = row_echelon(A[:, 1:])
        # Add the first zero-column back
        return np.hstack([A[:, :1], B])
    
    # If non-zero element happens not in the first row, switch rows
    if i > 0:
        ith_row = A[i].copy()
        A[i] = A[0]
        A[0] = ith_row
    
    # Divide first row by first element in it
    A[0] = A[0] / A[0, 0]
    
    # Subtract all subsequent rows with first row (it has 1 now as the first element)
    # multiplied by the corresponding element in the first column
    A[1:] -= A[0] * A[1:, 0:1]
    
    # Perform RREF on matrix from the second row, from the second column
    B = row_echelon(A[1:, 1:])
    
    # Add the first row and the first (zero) column, and return
    return np.vstack([A[:1], np.hstack([A[1:,:1], B])])

# Example 1
A = np.array([[1, 7, 4, 3],
              [0, 1, 2, 3],
              [3, 2, 0, 3],
              [1, 3, 1, 3]], dtype=np.float32)

# Example_2 random matrix
# m = 3
# n = 4
# A = np.random.rand(m, n)


print("Random matrix A:")
print(A)
print(" ")


# Print the reduced row echelon form
result = row_echelon(A)
print("Reduced Row Echelon Form:")
print(result)


Random matrix A:
[[1. 7. 4. 3.]
 [0. 1. 2. 3.]
 [3. 2. 0. 3.]
 [1. 3. 1. 3.]]
 
Reduced Row Echelon Form:
[[1.        7.        4.        3.       ]
 [0.        1.        2.        3.       ]
 [0.        0.        1.        1.9615384]
 [0.        0.        0.        1.       ]]


In [6]:
"""
Example 6.2.2:
SVD to find four fundamental basis, Null space as example. 
"""
import numpy as np
from numpy.linalg import matrix_rank
from numpy.linalg import svd

A = np.array([[1, 2, 3, 1], [1, 1, 2, 1], [1, 2, 3, 1]])
U, S, VH = svd(A)
r = matrix_rank(A)

print("rank = ", r)
print("U = \n", U) 
print("S = \n", S) 
print("VH = \n", VH) 

rank =  2
U = 
 [[ 6.38534846e-01  3.03765123e-01 -7.07106781e-01]
 [ 4.29588757e-01 -9.03024640e-01 -5.55111512e-16]
 [ 6.38534846e-01  3.03765123e-01  7.07106781e-01]]
S = 
 [6.06034043e+00 5.21798684e-01 3.75391546e-16]
VH = 
 [[ 0.28161099  0.49233672  0.77394771  0.28161099]
 [-0.56629961  0.59800046  0.03170085 -0.56629961]
 [ 0.74155675  0.080363   -0.080363   -0.66119374]
 [ 0.22381598  0.62732909 -0.62732909  0.40351311]]


In [13]:
"""
Example 6.2.3:
SVD to find four fundamental basis, Null space as example. 
Numerical Example from http://people.whitman.edu/~hundledr/courses/M240S16/M240/TheSVD.pdf 
"""
import numpy as np
from numpy.linalg import matrix_rank
from numpy.linalg import svd

A = np.array([[-3, 1], [6, -2], [6, -2]])
U, S, VH = svd(A)
r = matrix_rank(A)

print("rank = ", r)
print("U = \n", U) 
print("S = \n", S) 
print("VH = \n", VH) 

def null(A, eps=1e-15):
    U, S, VH = svd(A)
    null_mask = (S <= eps)
    null_space = np.compress(null_mask, VH, axis=0)
    return np.transpose(null_space)

null_space_matrix = null(A)
print("Null Space Matrix = \n", null_space_matrix) 



rank =  1
U = 
 [[-0.33333333  0.66666667  0.66666667]
 [ 0.66666667  0.66666667 -0.33333333]
 [ 0.66666667 -0.33333333  0.66666667]]
S = 
 [9.48683298 0.        ]
VH = 
 [[ 0.9486833  -0.31622777]
 [ 0.31622777  0.9486833 ]]
Null Space Matrix = 
 [[0.31622777]
 [0.9486833 ]]
