<!--NAVIGATION-->
< [4.1 Basics of Linear Algebra](Tien_chapter14.01-Basics-of-Linear-Algebra.ipynb) | [Contents](Tien_chapter14.02-Linear-Transformations.ipynb) | [4.3 Systems of Linear Equations](Tien_chapter14.03-Systems-of-Linear-Equations.ipynb) >

## **Lecture 4. Linear Algebra and Systems of Linear Equations:** 
### **4.2 Linear Transformations** 

For vectors $x$ and $y$, and scalars $a$ and $b$, it is sufficient to say that a function, $F$, is a **linear transformation** if  

<br>

$$
F(ax + by) = aF(x) + bF(y).
$$

<br>

<font color="magenta">**TRY IT!**</font> Let $x$ be a vector and let $F(x)$ be defined by $F(x) =y= Ax$ where $A$ is a rectangular matrix of appropriate size. Show that $F(x)$ is a linear transformation.


<font color="cyan">**Four important subpsaces associated with $y = Ax$:**</font>


* $x \in \mathcal{C}(\mathbf{A^T}) \subset {\mathbb{R^{n}}}$<br>  $x$ in row space
* $x_{null} \in \mathcal{N}(\mathbf{A}) \subset {\mathbb{R^{n}}}$<br> $x_{null}$ in null space 


* $y \in \mathcal{C}(\mathbf{A}) \subset {\mathbb{R^{m}}}$<br>  $y$ in column space
* $y_{leftnull} \in \mathcal{N}(\mathbf{A^T}) \subset {\mathbb{R^{m}}}$<br> $y_{leftnull}$ in left null space 

<font color="magenta">**TRY IT!**</font><br> Let $A = [[1, 0, 0], [0, 1, 0], [0, 0, 0]]$ and let the domain of $A$ be ${\mathbb{R}}^3$. Characterize the range (column space) and nullspace of $A$.
  
Let $v = [x,y,z]$ be a vector in ${\mathbb{R}}^3$. Then $u = Av$ is the vector $u = [x,y,0]$. Since $x,y\in {\mathbb{R}}$, the range of $A$ is the $x$-$y$ plane at $z = 0$.

Let $v = [0,0,z]$ for $z\in {\mathbb{R}}$. Then $u = Av$ is the vector $u = [0, 0, 0]$. Therefore, the nullspace of $A$ is the $z$-axis (i.e., the set of vectors $[0,0,z]$ $z\in {\mathbb{R}}$).

Therefore, this linear transformation "flattens" any $z$-component from a vector.

In [ ]:
"""
Example 4.14a:
N(A), Ax = 0. Note the inner matrix dimensions must match np.dot(A, x) 
"""
import numpy as np
from numpy.linalg import matrix_rank
from scipy.linalg import null_space

A = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 0]])
NS = null_space(A)
NS*np.sign(NS[0,0]) #remove the sign ambiguity of the vector

print("matrix_shape:", A.shape)
print("")
print("matrix_rank:", matrix_rank(A))
print("")
print("N(A) is:\n", NS)

# scipy.linalg.null_space
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.null_space.html 

In [3]:
"""
Example 4.14b:
Null space of A and Column space of A
The factor U will be of the same size as input matrix, but will be upper-triangular. 
In each row of U, pick the first nonzero element: these are pivot elements, which belong to linearly independent columns.
Gilbert Strang 3.6A   
"""
import numpy as np
from numpy.linalg import matrix_rank
from scipy.linalg import null_space, lu

A = np.array(np.dot([[1, 0, 0], [2, 1, 1], [5, 0, 1]], 
                    [[1, 3, 0, 5], [0, 0, 1, 6], [0, 0, 0, 0]]), dtype = float)
NS = null_space(A)
NS*np.sign(NS[0,0]) #remove the sign amBiguity of the vector

# print("matrix_shape:", A.shape)
# print("")
print("matrix_rank:", matrix_rank(A))
print("")
print("Null space is:\n", NS)
print("")


P, L, U = lu(A)

def get_indices_for_linearly_independent_columns_of_A(U):
    U_copy = U.copy()

    # Because some rows in U may not have even one nonzero element,
    # I have to find the index for the first one in two steps.
    index_of_all_nonzero_cols_in_each_row = [U_copy[i, :].nonzero()[0] for i in range(U_copy.shape[0])]
        
    index_of_first_nonzero_col_in_each_row = [indices[0] for indices in index_of_all_nonzero_cols_in_each_row if len(indices) > 0]
   
    return index_of_first_nonzero_col_in_each_row

CS = A[:, get_indices_for_linearly_independent_columns_of_A(U)]
print("Column space is: \n", CS)



matrix_rank: 2

Null space is:
 [[ 0.95093377 -0.04532191]
 [-0.28226221  0.27801091]
 [ 0.12497656  0.94645299]
 [-0.02082943 -0.15774217]]

Column space is: 
 [[1. 0.]
 [2. 1.]
 [5. 0.]]


In [13]:
"""
Example 4.14c:
Check the different bases of nullspace,
one is from hand calculation, the other one is from scipy.linalg.null_space(A)
"""
# check the coefficients aN1+bN2 = NS, where NS is from scipy.linalg.null_space(A)
# N1, N2 is from hand calculation

A = np.array([[-3, -5], [1, 0], [0, -6], [0, 1]])
y = np.array([[.95], [-.28], [.125], [-.02]])
x = np.linalg.pinv(A)@y
print(x)

N1 = np.array([-3,  1,  0,  0])
N2 = np.array([-5,  0, -6,  1])

x[0,:]*N1+x[1,:]*N2 

[[-0.28167089]
 [-0.02088608]]


array([ 0.94944304, -0.28167089,  0.12531646, -0.02088608])

<!--NAVIGATION-->
< [4.1 Basics of Linear Algebra](Tien_chapter14.01-Basics-of-Linear-Algebra.ipynb) | [Contents](Tien_chapter14.02-Linear-Transformations.ipynb) | [4.3 Systems of Linear Equations](Tien_chapter14.03-Systems-of-Linear-Equations.ipynb) >