## **Lecture 6. Linear Algebra and Systems of Linear Equations** 
### **6.4 Solving $Ax = y$ by library modules**

$$ 
\LARGE Ax=y 
$$ 

* $A$ is an $m \times n$ matrix with $rank(A) = r$

* **Solution** is an $x \in {\mathbb{R}}^n$ 

* **Measurement** $y \in {\mathbb{R}}^m$, 

* **Three Possibilities for Solution $x$**

<font color="cyan">**Case 1: There is a unique solution for $x$.**</font> 

Well-determined system: $ m = n = r, $ 

$y$ can be written as a linear combination of the columns of $A$. Matrix is **invertible**.

In [ ]:
"""
Example 6.4.1A:
Ax = y has a unique solution, Directed Inverse Method I by function call np.linalg.solve(A, y) 
Gilbert Strang Chap. 2
"""
import numpy as np

################################################
### 1. Augmented matrix A_y by concatenation ###
################################################ 
A = np.array([[1, 2, 1], [3, 8, 1], [0, 4, 1]])
y = np.array([[2], [12], [2]])
A_y = np.concatenate((A, y), axis = 1)
print(f"Augmented matrix A_y = \n{A_y}\n")
print(f"rank of A: {np.linalg.matrix_rank(A)} \n")
print(f"rank of A_y: {np.linalg.matrix_rank(A_y)} \n")

##################################################
### 2. Find the solution x by inverse method I ###
##################################################
x = np.linalg.solve(A, y)
print(f"solution x is = {x} \n")

#################################################################################################
### 3. check the result, Returns True if two arrays are element-wise equal within a tolerance ###
#################################################################################################
print(np.isclose(np.dot(A, x), y))   # element-wise comparision
print(np.allclose(np.dot(A, x), y))


Augmented matrix A_y = 
[[ 1  2  1  2]
 [ 3  8  1 12]
 [ 0  4  1  2]]

rank of A: 3 

rank of A_y: 3 

solution x is = [[ 2.]
 [ 1.]
 [-2.]] 

[[ True]
 [ True]
 [ True]]
True


In [ ]:
"""
Example 6.4.1B:
Ax = y has a unique solution, Directed Inverse Method II by np.linalg.inv(A)
Gilbert Strang Chap. 2
"""
import numpy as np

##########################################################
### 1. Augmented matrix A_y by broadcasting and hstack ###
##########################################################
A = np.array([[1, 2, 1], [3, 8, 1], [0, 4, 1]])
y = np.array([2, 12, 2])
A_y = np.hstack((A, y[:,None]))
print(f"Augmented matrix A_y = \n{A_y}\n")
print(f"rank of A: {np.linalg.matrix_rank(A)} \n")
print(f"rank of A_y: {np.linalg.matrix_rank(A_y)} \n")

###################################################
### 2. Find the solution x by inverse method II ###
###################################################
x = np.linalg.inv(A) @ y
print(f"solution x is: \n {x} \n")

#################################################################################################
### 3. check the result, Returns True if two arrays are element-wise equal within a tolerance ###
#################################################################################################
print(np.isclose(np.dot(A, x), y))   # element-wise comparision
print(np.allclose(np.dot(A, x), y))


Augmented matrix A_y = 
[[ 1  2  1  2]
 [ 3  8  1 12]
 [ 0  4  1  2]]

rank of A: 3 

rank of A_y: 3 

solution x is: 
 [ 2.  1. -2.] 

[ True  True  True]
True


In [33]:
"""
Example 6.4.1C:
Ax = y has a unique solution, Directed Inverse Method III by np.linalg.pinv(A)
Pseudo inverse pinv(A) is equal to inverse matrix inv(A)
Gilbert Strang Chap. 2
"""
import numpy as np

##########################################################
### 1. Augmented matrix A_y by broadcasting and hstack ###
##########################################################
A = np.array([[1, 2, 1], [3, 8, 1], [0, 4, 1]])
y = np.array([2, 12, 2])
A_y = np.hstack((A, y[:,None]))
print(f"Augmented matrix A_y = \n{A_y}\n")
print(f"rank of A: {np.linalg.matrix_rank(A)} \n")
print(f"rank of A_y: {np.linalg.matrix_rank(A_y)} \n")

####################################################
### 2. Find the solution x by inverse method III ###
####################################################
x = np.linalg.pinv(A) @ y
print(f"solution x is = {x} \n")

#################################################################################################
### 3. check the result, Returns True if two arrays are element-wise equal within a tolerance ###
#################################################################################################
print(np.isclose(np.dot(A, x), y))   # element-wise comparision
print(np.allclose(np.dot(A, x), y))

Augmented matrix A_y = 
[[ 1  2  1  2]
 [ 3  8  1 12]
 [ 0  4  1  2]]

rank of A: 3 

rank of A_y: 3 

solution x is = [ 2.  1. -2.] 

[ True  True  True]
True


<font color="cyan">**Case 2: There is no solution for $x$.** </font> 

Over-determined system:  $m>n=r, $ 

$y$ is linearly independent from the columns of $A$. 

Regression (projection) problem, least square method to find the approximation $\hat{x}$.

In [ ]:
"""
Example 6.4.2A: Directed Inverse Method by Projection Matrix
Ax = y has no solution, over-determined system, find the approximate solution x^
Gilbert Strang 4.2 Example 3
"""
import numpy as np
import numpy.linalg 

################################################
### 1. Augmented matrix A_y by concatenation ###
################################################ 
A = np.array([[1, 0], [1, 1], [1, 2]])
y = np.array([[6], [0], [0]])
A_y = np.concatenate((A, y), axis = 1)
print(f"Augmented matrix A_y = \n{A_y}\n")
print(f"rank of A: {np.linalg.matrix_rank(A)} \n")
print(f"rank of A_y: {np.linalg.matrix_rank(A_y)} \n")

##########################################################
### 2. Find the approximated solution x^ by projection ###
##########################################################
x = np.linalg.inv(A.T@A) @ A.T @ y
print(f"approximated solution x: \n {x} \n")

##################################################################################
### 3. check the result, p is the projected vector, P is the projection matrix ###
##################################################################################
P = A @ np.linalg.inv(A.T@A) @ A.T
p = np.dot(A,x)
r = np.linalg.matrix_rank(A_y)
e = np.dot((np.eye(r)-P), y)

print(f"projection matrix P: \n {P} \n")
print(f"projected vector p: \n {p} \n")
print(f"error vector e: \n {e} \n")
print(np.allclose(p + e, y))
print(np.isclose(p + e, y))


In [ ]:
"""
Example 6.4.2B: Directed Inverse Method by Psedo-inverse matrix pinv(A)
Ax = y has no solution, over-determined system, find the approximate solution x^
Gilbert Strang 4.2 Example 3
"""
##########################################################
### 1. Augmented matrix A_y by broadcasting and hstack ###
##########################################################
A = np.array([[1, 0], [1, 1], [1, 2]])
y = np.array([6, 0, 0], dtype=float)
A_y = np.hstack((A, y[:,None]))

#############################################################
### 2. Find the approximated solution x^ by pseduoinverse ###
#############################################################
x = np.linalg.pinv(A).dot(y)
print(x)
print(x.shape)
# note the shape of x is (2,): one-axis


<font color="cyan">**Case 3: There is an infinite number of solutions for $x$.**</font> 

Under-determined: $ m = r < n, $ 

$y$ can be written as a linear combination of pivot columns $x_p$ and free columns $x_n$, thus $A(x_p + x_n) = y$ 

In [ ]:
"""
Example 6.4.3A:
Ax = y has infinite solution, Directed Inverse Method by np.linalg.pinv(A) 
Gilbert Strang 3.4 Example 2
"""
import numpy as np

##########################################################
### 1. Augmented matrix A_y by broadcasting and hstack ###
##########################################################
A = np.array([[1, 1, 1], [1, 2, -1]])
y = np.array([3, 4]) 
A_y = np.hstack((A, y[:, None]))
print(f"rank of A is: {np.linalg.matrix_rank(A)} \n")
print(f"rank of A_y: {np.linalg.matrix_rank(A_y)} \n")

###########################################################
### 2. Find the particular solution xp by pseduoinverse ###
###########################################################
x = np.linalg.pinv(A)@y
print(f"solution xp: \n {x} \n")
print(f"minimal L2-norm of solution x = xp: {np.linalg.norm(x, 2)} \n")

#########################################
### 3. check the result, x = xp + xn  ###
#########################################
x_another = np.array([-1, 3, 1])
print(f"solution x = xp + xn: \n {x_another} \n")
print("L2-norm of solution x = xp + xn:", np.linalg.norm(x_another, 2))


---