## **Lecture 6. Linear Algebra and Systems of Linear Equations** 
### **6.4 Solving Systems of Linear Equations**

$$ 
\LARGE Ax=y 
$$ 

* $A$ is an $m \times n$ matrix with $rank(A) = r$

* **solution** is an $x \in {\mathbb{R}}^n$ 

* **measurement** $y \in {\mathbb{R}}^m$, three possible solutions for $x$. 

#### <font color="cyan">**6.4.1 Solve $Ax = y$ by library modules**</font> 

**Three Possibilities for Solution $x$**

<font color="cyan">**Case 1: There is no solution for $x$.** </font> 

Over-determined system:  $m>n=r, $ 

$y$ is linearly independent from the columns of $A$. 

Regression (projection) problem, least square method to find the approximation $\hat{x}$.

In [39]:
"""
Example 6.4.1A: Directed Inverse Method by Projection Matrix
Ax = y has no solution, over-determined system, find the approximate solution x^
Gilbert Strang 4.2 Example 3
"""
import numpy as np
import numpy.linalg 

A = np.array([[1, 0], [1, 1], [1, 2]])
# y = np.array([[6], [0], [0]])
# A_y = np.concatenate((A, y), axis = 1)
y = np.array([6, 0, 0], dtype=float)
A_y = np.hstack((A, y[:,None]))
print(f"Augmented matrix A_y = \n{A_y}\n")

# there are different approaches to find the projection matrix P = inv(A.T@A) @ A.T @ y
x = np.linalg.inv(A.T@A) @ A.T @ y
# x = np.dot(np.linalg.pinv(A), y)
print(f"rank of A: {np.linalg.matrix_rank(A)} \n")
print(f"rank of A_y: {np.linalg.matrix_rank(A_y)} \n")
print(f"approximated solution x: \n {x} \n")

# check the result, p is the projected vector, P is the projection matrix
p = np.dot(A,x)
print(f"projected vector p: \n {p} \n")

P = A @ np.linalg.inv(A.T@A) @ A.T
r = np.linalg.matrix_rank(A_y)
e = np.dot((np.eye(r)-P), y)
print(f"error vector e: \n {e} \n")

# check results
print(np.allclose(p + e, y))
print(np.isclose(p + e, y))


Augmented matrix A_y = 
[[1. 0. 6.]
 [1. 1. 0.]
 [1. 2. 0.]]

rank of A: 2 

rank of A_y: 3 

approximated solution x: 
 [ 5. -3.] 

projected vector p: 
 [ 5.  2. -1.] 

error vector e: 
 [ 1. -2.  1.] 

True
[ True  True  True]


In [25]:
"""
Example 6.4.1B: Directed Inverse Method by Psedo-inverse matrix pinv(A)
Ax = y has no solution, over-determined system, find the approximate solution x^
Gilbert Strang 4.2 Example 3
"""

A = np.array([[1, 0], [1, 1], [1, 2]])
y = np.array([6, 0, 0], dtype=float)
A_y = np.hstack((A, y[:,None]))

x = np.linalg.pinv(A).dot(y)
print(x)


[ 5. -3.]


<font color="cyan">**Case 2: There is a unique solution for $x$.**</font> 

Well-determined system: $ m = n = r, $ 

$y$ can be written as a linear combination of the columns of $A$. Matrix is **invertible**.

In [45]:
"""
Example 6.4.2A:
Ax = y has a unique solution, Directed Inverse Method by np.linalg.inv(A)
Gilbert Strang Chap. 2
"""
import numpy as np

A = np.array([[1, 2, 1], [3, 8, 1], [0, 4, 1]])
y = np.array([2, 12, 2])

x = np.linalg.inv(A) @ y
print(f"rank of A: {np.linalg.matrix_rank(A)}\n")
print(f"solution is: \n {x} \n")

# Returns True if two arrays are element-wise equal within a tolerance, 
# Check Ax == y
print(np.allclose(np.dot(A, x), y))


rank of A: 3

solution is: 
 [ 2.  1. -2.] 

True


In [43]:
"""
Example 6.4.2B:
Ax = y has a unique solution, Directed Inverse Method by np.linalg.solve(A) 
Gilbert Strang Chap. 2
"""
import numpy as np

A = np.array([[1, 2, 1], [3, 8, 1], [0, 4, 1]])
y = np.array([2, 12, 2])

x = np.linalg.solve(A, y)
print(f"solution is x = {x} \n")

# Returns True if two arrays are element-wise equal within a tolerance, 
# Check Ax == y
print(np.allclose(np.dot(A, x), y))

solution is x = [ 2.  1. -2.] 

True


In [46]:
"""
Example 6.4.2C:
Ax = y has a unique solution, Directed Inverse Method by np.linalg.pinv(A) 
Gilbert Strang Chap. 2
"""
import numpy as np

A = np.array([[1, 2, 1], [3, 8, 1], [0, 4, 1]])
y = np.array([2, 12, 2])

x = np.linalg.pinv(A) @ y
print(f"solution is x = {x} \n")

# Returns True if two arrays are element-wise equal within a tolerance, 
# Check Ax == y
print(np.allclose(np.dot(A, x), y))

solution is x = [ 2.  1. -2.] 

True


<font color="cyan">**Case 3: There is an infinite number of solutions for $x$.**</font> 

Under-determined: $ m = r < n, $ 

$y$ can be written as a linear combination of pivot columns $x_p$ and free columns $x_n$, thus $A(x_p + x_n) = y$ 

In [65]:
"""
Example 6.4.3A:
Ax = y has infinite solution, Directed Inverse Method by np.linalg.pinv(A) 
Gilbert Strang 3.4 Example 2
"""
import numpy as np

A = np.array([[1, 1, 1], [1, 2, -1]])
y = np.array([3, 4]) 
A_y = np.hstack((A, y[:,None]))

# rank(A_y) = r, means y is depdendent of columns of A 
print(f"rank of A is: {np.linalg.matrix_rank(A)} \n")
print(f"rank of A_y: {np.linalg.matrix_rank(A_y)} \n")

x = np.linalg.pinv(A)@y
print(f"solution xp: \n {x} \n")
print(f"minimal L2-norm of solution x = xp: {np.linalg.norm(x, 2)} \n")


#########################################################################
x_another = np.array([-1, 3, 1])
print(f"solution x = xp + xn: \n {x_another} \n")
print("L2-norm of solution x = xp + xn:", np.linalg.norm(x_another, 2))


rank of A is: 2 

rank of A_y: 2 

solution xp: 
 [1.14285714 1.57142857 0.28571429] 

minimal L2-norm of solution x = xp: 1.9639610121239313 

solution x = xp + xn: 
 [-1  3  1] 

L2-norm of solution x = xp + xn: 3.3166247903554


---