<!--NAVIGATION-->
< [4.4 Solutions to Systems of Linear Equations](Tien_chapter14.04-Solutions-to-Systems-of-Linear-Equations.ipynb)  | [Contents](Tien_chapter14.05-Solve-Systems-of-Linear-Equations-in-Python.ipynb) >

## **Lecture 4. Linear Algebra and Systems of Linear Equations:** 
### **4.5 Solve Systems of Linear Equations in Python**</font> 

Though we discussed various methods to solve the systems of linear equations, it is actually very easy to do it in Python. 

In this section, we will use Python to solve the systems of equations. The easiest way to get a solution is via the `solve` function in Numpy.linalg packages.


**Method 1:** Use `numpy.linalg.solve(A,y)` to solve the following equations.<br> 




$$
\begin{align}
4x_1 + 3x_2 - 5x_3 &=& 2 \\
-2x_1 - 4x_2 + 5x_3 &=& 5 \\
8x_1 + 8x_2  &=& -3 \\
\end{align}
$$

In [3]:
""" 
Example 4.27:
Solving Ax = b by numpy.linalg.solve(A,y), 
Under the hood, the solver is actually doing a LU decomposition to get the results.
"""
import numpy as np

A = np.array([[ 4,  3, -5], 
              [-2, -4,  5], 
              [ 8,  8,  0]])
y = np.array([[2], [5], [-3]])


x = np.linalg.solve(A, y)
print(x)

[[ 2.20833333]
 [-2.58333333]
 [-0.18333333]]


We get the same results as that in the previous section when we calculated by hand. 

____

**Method 2.** Using the matrix inversion approach. `numpy.linalg.inv(A)`

In [4]:
""" 
Example 4.28:
Solving Ax = b by numpy.linalg.inv(A), 
"""
import numpy as np

A = np.array([[ 4,  3, -5], 
              [-2, -4,  5], 
              [ 8,  8,  0]])
y = np.array([[2], [5], [-3]])

A_inv = np.linalg.inv(A)
x = np.dot(A_inv, y)
print(x)

[[ 2.20833333]
 [-2.58333333]
 [-0.18333333]]


**Method 3.** Use the `numpy.linalg.pinv(A)`

In [31]:
"""
Example 4.29:
Solving Ax = b and inverse by numpy.linalg.pinv(A)
Pseudo-inverse  
"""

### Pseudo-inverse A+
A_inv = np.linalg.pinv(A)
print(A_inv)
print("")

### solve Ax = y by A+y
x = np.linalg.pinv(A)@y
print(x)
print("")

### check A+ and A^-1 
print(np.isclose(np.linalg.pinv(A), np.linalg.inv(A)))


[[ 0.33333333  0.33333333  0.04166667]
 [-0.33333333 -0.33333333  0.08333333]
 [-0.13333333  0.06666667  0.08333333]]

[[ 2.20833333]
 [-2.58333333]
 [-0.18333333]]

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


**Method 4.** Use the `scipy.linalg.lu(A)`

In [12]:
""" 
Example 4.30:
check PA = LU, with scipy.linalg
pls refer to our function Example. 4.20 and 4.21
"""
import numpy
from scipy.linalg import lu

P, L, U = lu(A)
print('P:\n', P)
print('L:\n', L)
print('U:\n', U)


P:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L:
 [[ 1.    0.    0.  ]
 [-0.25  1.    0.  ]
 [ 0.5   0.5   1.  ]]
U:
 [[ 8.   8.   0. ]
 [ 0.  -2.   5. ]
 [ 0.   0.  -7.5]]


In [19]:
# check the PA and LU
PA = np.dot(P, A)
LU = np.dot(L, U) 

print(f"PA = \n {PA} \n")
print(f"LU = \n {LU} \n")

print(PA == LU)
print("")
# different object with same value
print(PA is LU)

PA = 
 [[ 8.  8.  0.]
 [-2. -4.  5.]
 [ 4.  3. -5.]] 

LU = 
 [[ 8.  8.  0.]
 [-2. -4.  5.]
 [ 4.  3. -5.]] 

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

False


#### **Problem 2: Incidence Matrix and Graph Problem**

 Consider the following network consisting of two power supply stations denoted by $S1$ and $S2$ and five power recipient nodes denoted by $N1$ to $N5$. The nodes are connected by power lines, which are denoted by arrows, and power can flow between nodes along these lines in both directions.

 Let $d_{i}$ be a positive scalar denoting the power demands for node $i$, and assume that this demand must be met exactly. The capacity of the power supply stations is denoted by $S$. Power supply stations must run at their capacity. For each arrow, let $f_{j}$ be the power flow along that arrow. Negative flow implies that power is running in the opposite direction of the arrow.
 
 <img src="./14.01.01-problem_11.png" alt="Problem 11" style="width: 400px;"/>

 Write a function *my_flow_calculator(S, d)*, where $S$ is a $1 \times 2$ vector representing the capacity of each power supply station, and $d$ is a $1 \times 5$ row vector representing the demands at each node (i.e., $d[0]$ is the demand at node 1). The output argument, $f$, should be a $1 \times 7$ row vector denoting the flows in the network (i.e., $f[0] = f_1$ in the diagram). The flows contained in $f$ should satisfy all constraints of the system, like power generation and demands. Note that there may be more than one solution to the system of equations.
 
 The total flow into a node must equal the total flow out of the node plus the demand; that is, for each node $i, f_{\text{inflow}} = f_{\text{outflow}} + d_{i}$. You may assume that $\Sigma{S_j} = \Sigma{d_i}$.

In [ ]:
## Test cases for problem 2

s = np.array([[10, 10]])
d = np.array([[4, 4, 4, 4, 4]])

# f = [[10.0, 4.0, -2.0, 4.5, 5.5, 2.5, 1.5]]
f = my_flow_calculator(s, d)

s = np.array([[10, 10]])
d = np.array([[3, 4, 5, 4, 4]])
# f = [[10.0, 5.0, -1.0, 4.5, 5.5, 2.5, 1.5]]
f = my_flow_calculator(s, d)

<!--NAVIGATION-->
< [4.4 Solutions to Systems of Linear Equations](Tien_chapter14.04-Solutions-to-Systems-of-Linear-Equations.ipynb)  | [Contents](Tien_chapter14.05-Solve-Systems-of-Linear-Equations-in-Python.ipynb)>