### **7.4 Eigenvalues and Eigenvectors in Python**

Though the methods we introduced so far look complicated, the actually calculation of the eigenvalues and eigenvectors in Python is fairly easy. 

The main <font color="cyan">built-in function</font> in Python to solve the eigenvalue/eigenvector problem for a square array is the *eig* function in numpy.linalg. Let's see how we can use it. 

**TRY IT** Calculate the eigenvalues and eigenvectors for matrix $A$: 
           
\begin{aligned}
8x_1 + 2x_2 + 3x_3   &=& 14 \\
2x_1 - 8x_2 + 5x_3  &=& 5 \\
3x_1 + 5x_2 + 10x_3 & =& -8 \\
\end{aligned}. 

In [ ]:
"""
Example 7.4.1: Build-in function to solve eigenvalues, eigenvectors 
"""
import numpy as np
from numpy.linalg import eig, cond

A = np.array([[8, 2, 3], [2, -8, 5], [3, 5, 10]], dtype=float)
w, v = eig(A)
print(f"E-value: \n{w}\n")
print(f"E-vector: \n{v}\n")


E-value: 
[13.4487556   5.93016383 -9.37891943]

E-vector: 
[[ 0.53416162  0.84246306  0.07019516]
 [ 0.23884925 -0.07074704 -0.96847607]
 [ 0.81093921 -0.53408881  0.23901203]]



In [ ]:
A = np.array([[0, 2], 
              [2, 3]])
w, v = eig(A) 
v = v*np.sign(v[0,0])     # remove the sign of ambiguity
print(f"E-value: \n{w}\n")
print(f"E-vector: \n{v}\n")

E-value: 
[-1.  4.]

E-vector: 
[[ 0.89442719  0.4472136 ]
 [-0.4472136   0.89442719]]

4.000000000000002


True