### **7.4 Eigenvalues and Eigenvectors in Python**

Though the methods we introduced so far look complicated, the actually calculation of the eigenvalues and eigenvectors in Python is fairly easy. 

The main <font color="cyan">built-in function</font> in Python to solve the eigenvalue/eigenvector problem for a square array is the *eig* function in numpy.linalg. Let's see how we can use it. 

**TRY IT** Calculate the eigenvalues and eigenvectors for matrix $A = \begin{bmatrix}
0 & 2\\
2 & 3\\
\end{bmatrix}$. 

In [1]:
"""
Example 7.4.1: Build-in function to solve eigenvalues, eigenvectors 
"""

import numpy as np
from numpy.linalg import eig, cond

In [27]:
A = np.array([[0, 2], 
              [2, 3]])
w, v = eig(A) 
v = v*np.sign(v[0,0])     # remove the sign of ambiguity
print(f"E-value: {w}\n")
print(f"E-vector: \n{v}\n")

print(cond(A))
np.allclose(abs(w[1])/abs(w[0]), cond(A))

E-value: [-1.  4.]

E-vector: 
[[ 0.89442719  0.4472136 ]
 [-0.4472136   0.89442719]]

4.000000000000002


True

In [2]:
"""
Example 7.4.2: Build-in function to solve eigenvalues, eigenvectors 
check other matrix (singular)
"""
A = np.array([[1, 1], 
              [1, 1.01]])
w, v = eig(A)
v = v*np.sign(v[0,0])     # remove the sign of ambiguity
print(f"E-value: {w}\n")
print(f"E-vector: \n{v}\n")

print(cond(A))
np.allclose(abs(w[1])/abs(w[0]), cond(A))



E-value: [0.0049875 2.0050125]

E-vector: 
[[ 0.70887232  0.70533682]
 [-0.70533682  0.70887232]]

402.0075124842952


True

**TRY IT!** Compute the eigenvalues and eigenvectors for matrix $A = \begin{bmatrix}
2 & 2 & 4\\
1 & 3 & 5\\
2 & 3 & 4\\
\end{bmatrix}$.

In [3]:
"""
Example 7.4.3: Build-in function to solve eigenvalues, eigenvectors with 3 by 3 matrix
True condition number sigma_max/sigma_min
"""


A = np.array([[2, 2, 4], 
              [1, 3, 5],
              [2, 3, 4]])
w, v = eig(A) 
v = v*np.sign(v[0,0])     # remove the sign of ambiguity
print(f"E-value: {w}\n")
print(f"E-vector: \n{v}\n")

print(cond(A))

E-value: [ 8.80916362  0.92620912 -0.73537273]

E-vector: 
[[ 0.52799324  0.77557092  0.36272811]
 [ 0.604391   -0.62277013  0.7103262 ]
 [ 0.59660259  0.10318482 -0.60321224]]

15.322938286261397


### **7.5 Singular Value Decomposition (SVD) in Python**

In [10]:
"""
Example 7.4.4: SVD and Condition number of Matrix A
"""
import numpy as np
from numpy.linalg import eig, cond, svd

# A = np.array([[ 1, -1], 
#               [-2,  2],
#               [ 2, -2]])

# U, S, VH = np.linalg.svd(A)

# print(f"U = \n{U}\n")
# print(f"S = \n{S}\n")
# print(f"VH = \n{VH}")


######### check the matrix condition number through SVD #################
A = np.array([[2, 2, 4], 
              [1, 3, 5],
              [2, 3, 4]])

U, S, VH = np.linalg.svd(A)

print(f"U = \n{U}\n")
print(f"S = \n{S}\n")
print(f"VH = \n{VH}\n")

print(f"condition number of matrix A is: {cond(A)}\n")
print(f"ratio of singular value is: {S[0]/S[2]}")


U = 
[[-0.52157957  0.51176432 -0.68268004]
 [-0.62993653 -0.7706383  -0.09641875]
 [-0.57544307  0.37975505  0.72432823]]

S = 
[9.30064272 1.06283875 0.60697515]

VH = 
[[-0.30363297 -0.50096516 -0.81045724]
 [ 0.95254376 -0.14030457 -0.27013886]
 [-0.02161931  0.85401905 -0.51979233]]

condition number of matrix A is: 15.322938286261397

ratio of singular value is: 15.322938286261403


In [6]:
"""
Example 5.8: 
"""



U = 
[[-0.52157957  0.51176432 -0.68268004]
 [-0.62993653 -0.7706383  -0.09641875]
 [-0.57544307  0.37975505  0.72432823]]

S = 
[9.30064272 1.06283875 0.60697515]

VH = 
[[-0.30363297 -0.50096516 -0.81045724]
 [ 0.95254376 -0.14030457 -0.27013886]
 [-0.02161931  0.85401905 -0.51979233]]


15.322938286261401