### **7.5 Singular Value Decomposition (SVD), Positive Definite Matrices, and Gradient Descent for Optimization**

For a symmetrix matrix $S = X\Lambda X^{T} = x_1\lambda_1 x_1^{T}+...+x_n\lambda_n x_n^{T}$
\begin{aligned}
8x_1 + 2x_2 + 3x_3   &=& 14 \\
2x_1 - 8x_2 + 5x_3  &=& 5 \\
3x_1 + 5x_2 + 10x_3 & =& -8 \\
\end{aligned}

<font color="magenta">**TRY IT!**</font> Compute the eigenvalues and eigenvectors for matrix $S = \begin{bmatrix}
8 & 2 &  3\\
2 & -8 & 5\\
3 & 5 & 10\\
\end{bmatrix}$.

In [11]:
"""
Example 7.5.1: Review of eigenvalues, eigenvectors with a 3 by 3 symmetric matrix S
"""
##########################################################
### 1. eigenvalue/eigenvector for a symmetric matrix S ###
##########################################################
import numpy as np
from numpy.linalg import eig

S = np.array([[8,  2,  3], 
              [2, -8,  5],
              [3,  5, 10]])
w, v = eig(S) 
v = v*np.sign(v[0,0])     # remove the sign of ambiguity
print(f"E-value w: {w}\n")
print(f"E-vector v: \n{v}\n")

E-value w: [13.4487556   5.93016383 -9.37891943]

E-vector v: 
[[ 0.53416162  0.84246306  0.07019516]
 [ 0.23884925 -0.07074704 -0.96847607]
 [ 0.81093921 -0.53408881  0.23901203]]



In [12]:
####################################################################
### 2. check orthogonality of eigenvectors of symmetric matrix S ###
####################################################################

def check_orthogonality(A, tol=1e-6):
    """
    Checks whether the columns of matrix A are orthogonal.
    :param A: Input matrix (numpy array)
    :param tol: Tolerance for numerical precision
    :return: True if columns are orthogonal, False otherwise
    """
    n = A.shape[1]  # Number of columns
    for i in range(n):
        for j in range(i + 1, n):
            dot_product = np.dot(A[:, i], A[:, j])
            if abs(dot_product) > tol:
                print(f"Columns {i+1} and {j+1} are NOT orthogonal (dot product: {dot_product:.6f})")
                return False
    print("Columns are orthogonal.")
    return True

# Check orthogonality
check_orthogonality(v)


Columns are orthogonal.


True

### <font color= "cyan">**7.5.1 Singular Value Decomposition (SVD) in Python**</font>
$A = U\Sigma V^{T} = u_1\sigma_1 v_1^{T}+...+ u_n\sigma_n v_n^{T}$

$S = X\Lambda X^{T} = x_1\lambda_1 x_1^{T}+...+x_n\lambda_n x_n^{T}$


In [15]:
"""
Example 7.5.2: SVD and Condition number of Matrix A
"""
import numpy as np
from numpy.linalg import eig, cond, svd

S = np.array([[8,  2,  3], 
              [2, -8,  5],
              [3,  5, 10]])

U, Sigma, VH = np.linalg.svd(S)

print(f"U = \n{U}\n")
print(f"Sigma = \n{Sigma}\n")
print(f"VH = \n{VH}\n")


######### check the matrix condition number through SVD #################

print(f"condition number of matrix S is: {cond(S)}\n")
print(f"ratio of singular value is: {Sigma[0]/Sigma[2]}")


U = 
[[-0.53416162  0.07019516 -0.84246306]
 [-0.23884925 -0.96847607  0.07074704]
 [-0.81093921  0.23901203  0.53408881]]

Sigma = 
[13.4487556   9.37891943  5.93016383]

VH = 
[[-0.53416162 -0.23884925 -0.81093921]
 [-0.07019516  0.96847607 -0.23901203]
 [-0.84246306  0.07074704  0.53408881]]

condition number of matrix S is: 2.267855661326328

ratio of singular value is: 2.267855661326327


____________

### <font color= "cyan">**7.5.2 Positive Definite Matrices $A^{T}A$**</font>
For a general matrix $Ax =b$
\begin{aligned}
1x_1 + 0x_2    &=& 6 \\
1x_1 + 1x_2    &=& 0 \\
1x_1 + 2x_2    &=& 0 \\
\end{aligned}

**TRY IT!** Compute the eigenvalues and eigenvectors for matrix $A = \begin{bmatrix}
1 & 0  \\
1 & 1  \\
1 & 2  \\
\end{bmatrix}$.

In [16]:
"""
Example 7.5.3: eigenvalues, eigenvectors with a 3 by 3 positive definite matrix A^TA
"""
##################################################################
### 1. eigenvalue/eigenvector for a positive definite matrix S ###
##################################################################
import numpy as np
from numpy.linalg import eig

A = np.array([[1,  0], 
              [1,  1],
              [1,  2]])
S = A.T @ A
w, v = eig(S) 
v = v*np.sign(v[0,0])            # remove the sign of ambiguity
print(f"E-value w: {w}\n")       # all positive e-values
print(f"E-vector v: \n{v}\n")

E-value w: [0.83772234 7.16227766]

E-vector v: 
[[ 0.81124219  0.58471028]
 [-0.58471028  0.81124219]]



In [20]:
"""
Example 7.5.4: SVD and Condition number of Positive definite Matrix S
"""
import numpy as np
from numpy.linalg import eig, cond, svd

A = np.array([[1,  0], 
              [1,  1],
              [1,  2]])
S = A.T @ A

U, Sigma, VH = np.linalg.svd(S)

print(f"U = \n{U}\n")
print(f"Sigma = \n{Sigma}\n")
print(f"VH = \n{VH}\n")

######### check the matrix condition number through SVD #################
print(f"condition number of matrix S is: {cond(S)}\n")
print(f"ratio of singular value is: {Sigma[0]/Sigma[1]}")


U = 
[[-0.58471028 -0.81124219]
 [-0.81124219  0.58471028]]

Sigma = 
[7.16227766 0.83772234]

VH = 
[[-0.58471028 -0.81124219]
 [-0.81124219  0.58471028]]

condition number of matrix S is: 8.549703546891168

ratio of singular value is: 8.54970354689117


### <font color= "cyan">**7.5.3 Optimization and Gradient Descent Method**</font>

\begin{aligned}
1x_1 + 0x_2   &=& 6 \\
1x_1 + 1x_2   &=& 0 \\
1x_1 + 2x_2   &=& 0 \\
\end{aligned}

A is a 3 by 2 matrix (more rows than columns), this is an over-determined system. 

The system may not have an exact solution, so we typically find the <font color=cyan> *Least Squares Solution* </font> that minimizes $J(x) = ||Ax-b||^2$. Let's compute the solution now. 

\begin{aligned}
 J(x) &= \frac{1}{2}||Ax-b||^2 \\
      &= \frac{1}{2}{(Ax-b)^T(Ax-b)} \\
      &= \frac{1}{2}{(x^TA^TAx-2x^TA^Tb+b^Tb)}\\
      &= \frac{1}{2}{x^TA^TAx}-x^TA^Tb+ \frac{1}{2}{b^Tb}\\
\\

\nabla{J(x)} &= AA^Tx -A^Tb = 0 \\    
\\
AA^Tx &= A^Tb 
\end{aligned}



Now the optimization problem leads to the classical $Sx = b'$ problem, now $S = A^TA$ is a positice definite matrix, $b' = A^Tb$ is the new vector. 
\begin{aligned}
Sx = b'
\end{aligned}

This $Sx = b'$ problem can be solved by the numerical gradient descent method. 

In [22]:
"""
Example 7.5.5: Optimization to find the least square solution
"""

A = np.array([[1,  0], 
              [1,  1],
              [1,  2]])
b = np.array([6, 0, 0])

S = A.T @ A
b_new = A.T @ b

x = np.linalg.pinv(S) @ b_new
print(f"solution x is = {x} \n")



solution x is = [ 5. -3.] 



In [24]:
"""
Example 7.5.6: Optimization by gradient descent
"""
import numpy as np

def gradient_descent(A, b, x_init, learning_rate=0.01, tol=1e-6, max_iter=1000):
    x = x_init
    for i in range(max_iter):
        gradient = 2 * A.T @ (A @ x - b)  # Compute gradient
        x_new = x - learning_rate * gradient  # Update step
        
        if np.linalg.norm(x_new - x, ord=2) < tol:  # Convergence check
            break
        x = x_new
    return x

# Example 2x2 system

x_init = np.zeros(2)  # Initial guess
solution = gradient_descent(S, b_new, x_init)
print("Solution x:", solution)


Solution x: [ 4.99994296 -2.99995889]
